# Generated by Django 5.1.6 on 2025-03-30 16:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Title of duty', unique=True)),
                ('team', models.JSONField(help_text="List of team (e.g. ['Ivan', 'Maria', 'Petr'])")),
                ('duty_duration', models.PositiveIntegerField(choices=[(1, '1 day'), (7, '1 week'), (14, '2 weeks')], help_text='Duty duration')),
                ('header_text', models.TextField(help_text='Default header text (used if no overwrite is provided)')),
                ('footer_text', models.TextField(blank=True, help_text='Default footer text (used if no overwrite is provided)', null=True)),
                ('channel_id', models.CharField(blank=True, help_text='ID of the channel to send the message', max_length=255, null=True)),
                ('sprint_start_date', models.DateField(blank=True, help_text='For 7-day and 14-day schedules: start date of the current sprint', null=True)),
                ('first_week', models.JSONField(blank=True, help_text='Overwrite for first week (e.g. {0: {"header": None, "footer": None, "send": False, "mention": None, "keep_random": False}})', null=True)),
                ('second_week', models.JSONField(blank=True, help_text='Overwrite for first week (e.g. {0: {"header": None, "footer": None, "send": False, "mention": None, "keep_random": False}})', null=True)),
                ('last_modified_by', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duty_person', models.CharField(max_length=255)),
                ('random', models.BooleanField(default=False)),
                ('header_text', models.TextField()),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('send', models.BooleanField(default=False)),
                ('mention', models.BooleanField(default=False)),
                ('keep_random', models.BooleanField(default=False)),
                ('last_modified_by', models.EmailField(max_length=254, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dutyapp.dutyconfig')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDutyConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.TextField(db_index=True, help_text='Title of duty')),
                ('team', models.JSONField(help_text="List of team (e.g. ['Ivan', 'Maria', 'Petr'])")),
                ('duty_duration', models.PositiveIntegerField(choices=[(1, '1 day'), (7, '1 week'), (14, '2 weeks')], help_text='Duty duration')),
                ('header_text', models.TextField(help_text='Default header text (used if no overwrite is provided)')),
                ('footer_text', models.TextField(blank=True, help_text='Default footer text (used if no overwrite is provided)', null=True)),
                ('channel_id', models.CharField(blank=True, help_text='ID of the channel to send the message', max_length=255, null=True)),
                ('sprint_start_date', models.DateField(blank=True, help_text='For 7-day and 14-day schedules: start date of the current sprint', null=True)),
                ('first_week', models.JSONField(blank=True, help_text='Overwrite for first week (e.g. {0: {"header": None, "footer": None, "send": False, "mention": None, "keep_random": False}})', null=True)),
                ('second_week', models.JSONField(blank=True, help_text='Overwrite for first week (e.g. {0: {"header": None, "footer": None, "send": False, "mention": None, "keep_random": False}})', null=True)),
                ('last_modified_by', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical duty config',
                'verbose_name_plural': 'historical duty configs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
