
stages:
  - test
  - build

test:
  image: python:3.11-slim
  stage: test
  script:
    - python manage.py test
  artifacts:
    when: always
    paths:
      - test-reports/

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t my-django-app .
    - docker images
  artifacts:
    paths:
      - my-django-app-image.tar
  only:
    - master