version: '3'

services:

  web:
    build:
      context: ./dutyproject
      dockerfile: Dockerfile
    environment:
      DOCKER_TLS_CERTDIR: ""
      ENGINE: <YOUR_ENGINE> 
      DB_NAME: <YOUR_DB_NAME> 
      DB_USER: <YOUR_DB_USER> 
      DB_PASSWORD: <YOUR_DB_PASSWORD> 
      DB_HOST: <YOUR_DB_HOST> 
      DB_PORT: <YOUR_DB_PORT> 
      API_PERMANENT_TOKEN: <YOUR_API_PERMANENT_TOKEN> 
      SLACK_TOKEN: <YOUR_SLACK_TOKEN> 
      SECRET_KEY: <YOUR_SECRET_KEY>
    ports:
      - "8000:8000"
    volumes:
      - ./dutyproject:/app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  cron:
    build:
      context: ./dutyproject
      dockerfile: Dockerfile
    volumes:
      - .:/code
    entrypoint: >
      /bin/sh -c "echo '0 0 1 1 * cd /code && /usr/local/bin/python manage.py recalculate_schedules' > /etc/cron.d/recalculate &&
      chmod 0644 /etc/cron.d/recalculate &&
      crontab /etc/cron.d/recalculate &&
      crond -f -L /dev/stdout"
